name: "Deploy to Google Cloud Functions"

on:
  push:
    branches:
      - master

jobs:
    deploy:
      runs-on: 'ubuntu-latest'
      permissions:
        contents: 'read'
        id-token: 'write'
  
      steps:
      - uses: 'actions/checkout@v3'
  
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_RAW }}'
  
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'inventory-record-removal'
          runtime: 'python39'
          entry_point: 'main'
        #   event_trigger_type: 'google.pubsub.topic.publish'
          https_trigger_security_level: 'SECURE_ALWAYS'
          ingress_settings: 'INTERNAL_ONLY'
        #   event_trigger_resource: 'projects/${{ secrets.GCP_PROJECT }}/topics/inventory-record-removal'
  